### ISSUE TITLE
[frenap] 'edge_id' error when querying mongodb

### ISSUE THREAD

**Issue by hawesie** [strands-project/fremen#10]
I see lots of the following when running with the mdp nodes which talk to frenap:

```
[ERROR] [1427404235.046518000]: Service call failed: service [/message_store/query_messages] responded with an error: error processing request: 'edge_id'
```

Mongo also isn't happy:

```
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/site-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/opt/ros/indigo/lib/mongodb_store/message_store_node.py", line 213, in query_messages_ros_srv\n    message = dc_util.dictionary_to_message(entry, cls)\n', '  File "/opt/ros/indigo/lib/python2.7/site-packages/mongodb_store/util.py", line 314, in dictionary_to_message\n    fill_message(message, dictionary)\n', '  File "/opt/ros/indigo/lib/python2.7/site-packages/mongodb_store/util.py", line 265, in fill_message\n    value = document[slot]\n', "KeyError: 'edge_id'\n"]
```

**Comment by hawesie** [comment]
This seems to have gone away now, probably due to updates in strands_navigation.
